# Active Profile (defaults to dev for your local machine)
spring.profiles.active=dev

# Common App Settings
spring.application.name=Tasksphere
spring.jackson.deserialization.fail-on-null-for-primitives=false