spring.application.name=Tasksphere
spring.datasource.url=jdbc:postgresql://localhost:5432/tasksphere_db
spring.datasource.username=postgres
spring.datasource.password=sam@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Open Session in View to avoid holding DB connections open during rendering
spring.jpa.open-in-view=false

# JWT Security
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring.jackson.deserialization.fail-on-null-for-primitives=false
# Spring Mail Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=c1c6e18bfd1b6d
spring.mail.password=e4ffce475be976
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true