CREATE TABLE projects
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    archived BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);